export default {
	TableColumns: {
		statistics: [{
			title: '구분',
			key: 'date',
			button: false,
		}, {
			title: '구분',
			key: 'month',
			button: false,
		}, {
			title: '매체명',
			key: 'media',
			button: false,
		}, {
			title: '플레이스/상품명',
			key: 'company_nm',
			button: false,
		}, {
			title: '키워드',
			key: 'keyword',
			button: false,
		}, {
			title: '상품유형',
			key: 'prd_type',
			button: false,
		}, {
			title: '클릭수',
			key: 'click',
			button: false,
			number: true,
			essential: true,
		}, {
			title: '참여수',
			key: 'mission',
			button: false,
			number: true,
			essential: true,
		}, {
			title: '소진금액',
			key: 'cost',
			button: false,
			number: true,
			essential: true,
			auth: ['관리자'],
		}, {
			title: '매체금액',
			key: 'cost_media',
			button: false,
			number: true,
			essential: true,
			auth: ['관리자'],
		}, {
			title: '수익',
			key: 'profit',
			button: false,
			number: true,
			essential: true,
		}],
		detail: [{
			title: '구분',
			key: 'createdAt',
			button: false,
		}, {
			title: '플레이스/상품명',
			key: 'company_nm',
			button: false,
		}, {
			title: '키워드',
			key: 'keyword',
			button: false,
		}, {
			title: '상품유형',
			key: 'prd_type',
			button: false,
		}, {
			title: 'PID',
			key: 'pid',
			button: false,
		}, {
			title: 'MID',
			key: 'mid',
			button: false,
		}, {
			title: '매체명',
			key: 'media',
			button: false,
			auth: ['관리자', '광고주'],
		}, {
			title: 'ADID',
			key: 'adInfoId',
			button: false,
		}, {
			title: 'IP',
			key: 'ip',
			button: false,
		}, ],
	}
};